### PR TITLE
threads: Remove all the modules except Mutex and Delay

### PR DESCRIPTION
**Pull request by psafont**
These modules are barely used and are problematic because they need much
testing with the coming ocaml 5.0

Change the opam metadata, generate it using dune. This creates more structured metadata and should be easier to maintain because it doesn't need to duplicate information shared between all the packages.

### CODE REVIEW

**Comment by lindig** [comment]
That sounds good. But don't we have to update clients first to not use any of the modules that are going to be removed?

**Comment by psafont** [comment]
Absolutely: we've merged the change already: https://github.com/xapi-project/xen-api/pull/4733

**Comment by robhoes** [comment]
>threads: Remove all the modules except Mutex

...and `Delay` :)

**Review by robhoes — APPROVED** [review]

**Review by edwintorok — APPROVED** [review]
Please update the title as suggested by Rob, we do need to keep the Delay module

**Pull request merged**
