### PR TITLE
Port to jbuilder

### PR DESCRIPTION
**Pull request by mseri**
This will require renaming `xapi-stdext` to `stdext`.

To avoid breaking compatibility, in my environment I have `stdext` pinned to this repo and `xapi-stdext` pinned to the following opam file:
```
opam-version: "1.2"
maintainer: "jonathan.ludlam@citrix.com"
authors: "xen-api@list.xen.org"
bug-reports: "https://github.com/xapi-project/stdext/issues"
dev-repo: "git://github.com/xapi-project/stdext.git"
homepage: "https://xapi-project.github.io/"
tags: [ "org:xapi-project" ]
depends: [
  "stdext"
]
```

### CODE REVIEW

**Comment by gaborigloi** [comment]
Looks good, just a few questions:
* So will the deleted unused tests be readded at some point?
* Also, I think this is a breaking change, because we turned some of the polymorpic types into `unit` in the `mli`s, so we'll have to bump the major version number I guess. Is it possible that this will cause some code in our components to break?

**Comment by mseri** [comment]
No, I'd rather remove the library (also they were rubbish)

**Comment by mseri** [comment]
I can confirm that `opam list --rec --depends-on xapi-stdext --short | xargs opam install -y` (using the double pinning mentioned above) worked

**Comment by mseri** [comment]
I want to take this opportunity to remove all the unused modules. Please do not merge for the moment. I am going to close the PR and reopen it once they are all out of our sight :dagger: :smile:

**Comment by mseri** [comment]
This is my current suggestion for refactoring stdext and being able to slowly deprecate it.
The current version, after pinning all the new `xapi-stdext-` packages can be used to compile everything that was depending on stdext without changes.

Some of the remaining libraries are barely used (e.g. Zerocheck is used only in ocaml/xapi/stream_vdi.ml#L159 or ), some are used in a scattered way and other are extensively used (e.g. Listext, Unixext and Stringext). We can definitely remove a few more with not much effort, but with necessary changes in some of our libraries. I believe this refactoring will make it easier to use specific libraries in specific places and reduce `stdext` further and get rid of unnecessary dependencies.

**Comment by mseri** [comment]
If we accept this, we will need to release the following:
```
xapi-stdext 3.0
xapi-stdext-base64 1.0
xapi-stdext-bigbuffer 1.0
xapi-stdext-date 1.0
xapi-stdext-deprecated 1.0
xapi-stdext-encodings 1.0
xapi-stdext-monadic 1.0
xapi-stdext-pervasives 1.0
xapi-stdext-range 1.0
xapi-stdext-std 1.0
xapi-stdext-threads 1.0
xapi-stdext-unix 1.0
xapi-stdext-zerocheck 1.0
```

**Comment by lindig** [comment]
In general, I believe we should take this PR because it offers the chance to gradually remove or replace unused and bad code. The change does not break existing code and the commits do not change behaviour.

**Comment by mseri** [comment]
I am going to merge and prepare a release. I will submit the necessary changes for `xs-opam` soon after

**Pull request merged**
